program: models/wandb_run.py
method: bayes
metric:
  name: avg_rank
  goal: minimize
parameters:
  # hyperparameters start with overrides
  # Ranges
  overrides.dataset_reader.number_negative_samples:
    min: 1
    max: 2
  overrides.trainer.optimizer.lr:
    min: -7.0
    max: 0
    distribution: log_uniform
  overrides.model.softbox_temp:
    min: 10
    max: 50
    distribution: uniform
  # mandatory parameters with fixed names
  local_config_file:
    value: "/Users/dhruv/UnsyncedDocuments/IESL/kb_completion/models/configs/default_training_with_rank_validation_with_wandb_log.json"
  subcommand:
    value: train
