program: models/wandb_run.py
method: bayes
metric:
  name: avg_rank
  goal: minimize
parameters:
  # hyperparameters start with overrides
  # Ranges
  overrides.dataset_reader.number_negative_samples:
    min: 1
    max: 20
    distribution: q_uniform
  overrides.trainer.optimizer.lr:
    min: -7.0
    max: -3.2
    distribution: log_uniform
  overrides.model.type:
    value: max-margin-conditional-box-model
  overrides.model.box_type:
    value: SigmoidBoxTensor
  overrides.model.softbox_temp:
    min: 10
    max: 50
    distribution: uniform
  overrides.model.margin:
    min: 0.0
    max: 4.6
    distribution: log_uniform
  overrides.model.embedding_dim:
    values: [50, 100, 150, 200]
  overrides.iterator.batch_size:
    values: [32, 128, 512, 2048, 8192]
  # mandatory parameters with fixed names
  local_config_file:
    value: "/mnt/nfs/work1/mccallum/dhruveshpate/kb_completion/models/configs/gypsum_default_training_with_rank_validation_with_wandb_log_tb_logging_debugi_WN.json"
  subcommand:
    value: train
  # params to pass as args to wandb.run object
  tags:
    value: "head_to_tail,conditional,max_margin,SigmoidBoxTensor,val_avg_rank"
    # format: exact score calculation, conditional or not, loss, box_type,val metric
